# Generated by Django 5.0.2 on 2024-02-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productaccess',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
