# Generated by Django 5.0.2 on 2024-02-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_productaccess_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaccess',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
