# Generated by Django 5.0.2 on 2024-02-29 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productaccess_user'),
        ('study', '0007_group_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
    ]
